import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:gap/gap.dart';
import 'package:travel_hero/src/application/itinerary/create_itinerary_cubit.dart';
import 'package:travel_hero/widgets/app_box_loading.dart';
import 'package:travel_hero/widgets/create_trip_plan_app_bar.dart';
import 'package:widgets_book/widgets_book.dart';

class GeneratingTripPlanPage extends StatefulWidget {
  const GeneratingTripPlanPage({super.key});

  @override
  State<GeneratingTripPlanPage> createState() => _GeneratingTripPlanPageState();
}

class _GeneratingTripPlanPageState extends State<GeneratingTripPlanPage> {
  @override
  void initState() {
    super.initState();
    context.read<CreateItineraryCubit>().createOpenAiItinerary();
  }

  @override
  Widget build(BuildContext context) {
    return BaseScaffold(
      backgroundColor: Colors.white,
      body: Column(
        children: [
          Gap(50.h),
          CreateTripPlanAppBar(
            showProgressBar: true,
            current: 3,
            titleText: 'Create a Trip Plan',
            stepText: 'Generating Trip Plan',
            subTitleText:
                'Generating the Trip Plan through the magical AI, Please wait',
            max: 4,
          ),
          Gap(16.h),
          Expanded(
            child: AppBoxLoading(
              title: 'Generating Trip Plan',
              subTitle:
                  'Please wait, your Trip Plan is being generated by\nmagic AI. This could take a couple of minutes',
            ),
          ),
        ],
      ),
    );
  }
}
